###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    # mailhog:
    #   image: mailhog/mailhog:latest
    #   container_name: laravel-starter-mailhog
    #   ports:
    #     - "8081:8025"

    mysql:
      image: mysql:5.7
      container_name: demo-laravel-medialibrary-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=admin_starter
        - MYSQL_USER=admin_starter
        - MYSQL_PASSWORD=1234
      # ports:
      #   - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: demo-laravel-medialibrary-webserver
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: demo-laravel-medialibrary-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

